name: Build
on: [push]

jobs:
  Build:
    strategy:
      matrix:
        lecture: [ComGra, PmQm]
        version: [summary, cheatsheet]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install texlive texlive-latex-extra texlive-extra-utils
          npm install

      - name: Build
        run: make ${{ matrix.version }} lecture=${{ matrix.lecture }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.lecture }}-${{matrix.version}}
          path: ${{ matrix.lecture }}/*.pdf
